[package]
name = "coalescence_common"
description = "Shared types and logic between client and server"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
