[package]
name = "multiplayer_mvp_native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies.bevy]
# version = "0.11"
path = "/home/ts/dev/rust/bevyengine/bevy"
default-features = false
features = ["multi-threaded"]
