[package]
name = "multiplayer_mvp_common"
description = "Common functionality shared by the client and the server"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
serde = "1.0"
